### ISSUE TITLE
Release date?

### ISSUE THREAD

**Issue by bellamystudio** [louisameline/tooltipster-follower#1]
Hi - I was implementing tooltipster on a project and really needed the tooltip to show up where the pointer is. By complete coincidence you checked this in yesterday(!), and I was just wondering if you had any idea when it might be ready (even for testing?)

**Comment by louisameline** [comment]
Hi, I'm working on this right now. I'll release a pre-alpha by tomorrow if you want ;)

**Comment by bellamystudio** [comment]
That would be amazing 😃

**Comment by bellamystudio** [comment]
If the offer of an alpha test still stands, I'm happy to test! How's it
going? :)

**Comment by louisameline** [comment]
Give me one more hour :+1:

**Comment by louisameline** [comment]
It looks like this: http://louisameline.github.io/tooltipster-follower/demo/

It's still WIP: I need to listen to mousemove events as soon as the origin is hovered and support position:fixed elements. If you have ideas about options that would be cool, let me know!

**Comment by bellamystudio** [comment]
Wow that's working _really_ well! It's actually doing all I need it to do
right now - but if I think of useful options I'll send ideas through!

**Comment by louisameline** [comment]
Cool :) I'll be finished by tomorrow I guess (documentation and bug fixes).

**Comment by louisameline** [comment]
I think I'm done! Feel free to open issues if you have feedback. Thank you

**Comment by bellamystudio** [comment]
Oh no I can't get this to work! I can see it has a dependency on the v4 branch, but if I use that I can't seem to make AJAX calls to tooltip content ( `continueTooltip() is not a function` ). 

Does v3.3.0 (current master branch) support plugins? Has AJAX support been dropped by v4?

Sorry about all the questions!

**Comment by louisameline** [comment]
No problem! There are breaking changes in v4. Its documentation is included (check out the index.html file). The signature of callbacks has changed, for example:

``` javascript
functionBefore: function(origin, continueTooltip) {
    origin.tooltipster('content', 'Hello world');
    origin.css('opacity', 0.5);
    continueTooltip();
}
```

becomes

``` javascript
functionBefore: function(instance, helper) {
    instance.content('Hello world');
    $(helper.origin).css('opacity', 0.5);
    // you can return false to prevent the tooltip from opening
    return true;
}
```

**Comment by bellamystudio** [comment]
This is working brilliantly Louis :D I have one more question - when I load the content via AJAX my 'loading' tooltip disappears and I have to move the pointer to make the populated tooltip appear. What am I doing wrong?

```
    $('.part-tooltip').tooltipster({
        content: preLoaderHTML,
        position: 'top right',
        arrow: false,
        maxWidth: 600,
        contentAsHTML: true,
        plugins: ['laa.follower'],
        functionBefore: function(instance, helper) {

               var $origin = $(helper.origin);
               var bikePart = ($origin.attr('id'));
               var partUrl = '/bikes-kit/part/'+bikePart;
               // we set a variable so the data is only loaded once via Ajax, not every time the tooltip opens
               if ($origin.data('loaded') !== true) {
                   $.get(partUrl, function(data) {
                       // call the 'content' method to update the content of our tooltip with the returned data
                       instance.content(data);
                       // to remember that the data has been loaded
                       $origin.data('loaded', true).data('ajax', 'cached');
                   });
               }
           }
    });
```

**Comment by louisameline** [comment]
Thank you! Ha, good catch. I need to fix this, hold on.

**Comment by louisameline** [comment]
You can pull the latest version of both Tooltipster and Follower. Thanks!

**Comment by bellamystudio** [comment]
Pulled both and the fix works!! Thank you! :)
