### ISSUE TITLE
Tooltip already destroyed

### ISSUE THREAD

**Issue by hardcoremore** [louisameline/tooltipster-follower#2]
There is a bug after element on which tooltipster is initialized is removed when using follower plugin. On line 181 in function __destroy it calls this.__instance.option('repositionOnScroll', false) after which tooltipster throws an error that plugin is already destroyed.

```
 __destroy: function() {

            this.__instance._off('.'+ this.__namespace);

            if (!this.__initialROS) {
                //this.__instance.option('repositionOnScroll', false); // there is a bug saying that tooltipster is already close when calling this method.
            }

            return this;
        },
```

**Comment by louisameline** [comment]
Thanks for the report! Please pull the updated Tooltipster 4.0.3 and Follower 0.1.1 repos and this should be fixed.

**Comment by hardcoremore** [comment]
Hey I do not have configured project and the dist folder is not updated with latest builds. It still says 4.0.2. Can you please build and commit latest code.

Thanks

**Comment by louisameline** [comment]
I forgot to edit the package.json but it's built. I'll add a grunt task to make sure it doesn't happen again. I'll bump in the morning.

**Comment by hardcoremore** [comment]
Thanks a lot. It works great now :)
