### ISSUE TITLE
triggerClose - disable reposition

### ISSUE THREAD

**Issue by speckis** [louisameline/tooltipster-follower#3]
When I close the tooltip on mobile/pad, it repositions itself where my click is before disappearing. 

The positioning following my mouse when it opens doesn't matter - only when it closes. Is there a way to disable that? 

Thanks in advance!

**Comment by louisameline** [comment]
Hi,

I'm not sure I understand. You'd like : 
- the tooltip to open when you hover with your finger
- the tooltip to follow your finger while you move it
- the tooltip to stay on screen after you released your finger
- the tooltip to disappear when you touch the screen again, but without repositiong

is that it?

**Comment by speckis** [comment]
No, maybe I explained badly. I'm only talking about mobile and ipad devices
- where you can't hover, only 'click' or 'tap'.

Now if I click, the tooltip will appear. And stay there, because of course
there is no hover on those devices. Here is the problem:
- When I close the tooltip, it will quickly jump to where I click to close
  it and disappear.

I want it to disappear where it appeared. To ignore my mouse position when
I close it.

Was this better, or did I make it worse? (Love the plugin, btw)
Den 5 jul 2016 18:20 skrev "Louis Ameline" notifications@github.com:

**Comment by louisameline** [comment]
Thank you :)

I see. But opening a "following tooltip" on tap kind of defeats the purpose of `follower`, doesn't it? Since there is indeed nothing to follow. A default Tooltipster tooltip would be better for touch devices then, wouldn't it?

It's actually already possible to activate Tooltipster's `sideTip` on mouse events and `follower` on touch events, but it's not the most simple thing right now. I'll think about it tomorrow. Your thoughts on the subject are welcome :)

> because of course there is no hover on those devices

Note that it's actually possible that the tooltip follows the finger (what you call 'hover' I presume) if scrolling is prevented.

**Comment by speckis** [comment]
Okay, thank you! Thing is, I need the follower on desktop, where it works perfectly. 

You said something about activating different plugins on different triggers? Or did I understand that wrong, because that would solve the problem I think.

**Comment by louisameline** [comment]
There is no built-in system to activate different plugins on different triggers, but it should be possible to achieve it with the "_plug" and "_unplug" methods, which allow to manage plugins manually. But it may be challenging to set up.

Hey, I just had an idea. What about having two tooltips: one using `follower` and the `mouseenter` open trigger (for desktop), and the other one using `sideTip` and the `tap` open trigger (for mobile devices)? It would actually be more straightforward than having a single tooltip that changes its behavior during its course of action, wouldn't it?

**Comment by louisameline** [comment]
Your initial idea is also possible: when `follower` is used with the `tap` close trigger, the `touchstart` event of the tap should be ignored, thus avoiding the repositioning. I'm just wondering if someone could have a use case where it should not be ignored. Maybe I could make your proposition the default behavior and add an option to make the other behavior possible.

**Comment by speckis** [comment]
Thank you for the deep replies! 

I also think it would be better by making it default - because the repositioning when closing on tap is not that user-friendly, and a little disorienting. 

If you made it default it would be really cool! I honestly think this might be the best, or at least most comfortable, plugin I've worked with. Love your documentation.

**Comment by louisameline** [comment]
Thank you very much, I appreciate :)
I'll do the modification shortly.

**Comment by speckis** [comment]
Awesome! Please tell me when you are done! :)

**Comment by louisameline** [comment]
GitHub closed this issue automatically just by reading the title of my commit, didn't know it could do that! Anyway, I think it works now, can you check for yourself please?

But I noticed a bug in iOS when the trigger is `hover` - mobile browsers are a PITA - I got myself some more work to do :/
