### ISSUE TITLE
Click option has issue on IE

### ISSUE THREAD

**Issue by PavelBrokhman** [louisameline/tooltipster-follower#5]
Hi guys,

We have tried to implements next logic:

```
<script>
        $(document).ready(function() {

        $('.tooltip').tooltipster({
        plugins: ['follower'],
        trigger: 'custom',
    triggerOpen: {
        click: true,
        //mouseenter: true,
        touchstart: true
    },
    triggerClose: {
        mouseleave: true,
        click:true,
        scroll: true,
        tap: true
    }
        });

        });


    </script>

<map name="planetmap">
 <span class="tooltip" title="Rectangle"> <area shape="rect" coords="0,0,82,126" ></span>
 <span class="tooltip" title="Circle Mercury"> <area shape="circle" coords="90,58,3" > <span> 
 <span class="tooltip" title="Circle Venus">   <area shape="circle" coords="124,58,8" > <span> 
</map>

```

It works properly on Chrome and Firefox. We click on the area and tooltip is shown. When we try to do the same on IE it doesn't work on the click. We have first to do even small mouse moving and then we see the tooltip.

The same issue happens even I do as simple as this one
`<span class="tooltip"  title="Any Tooltip">Tooltip</span>`

I have opened it in [here](https://github.com/iamceege/tooltipster/issues/586#issuecomment-238390821) and succeeded to reproduce it. Can you look at it? When I debugged it I saw that on the first click display attribute is none.

**Comment by louisameline** [comment]
Should work now in v0.1.4, thank you for the report!
